version: 2
jobs:
  build:
    docker:
      - image: qawolf/playwright-ci:v1.0.0
    steps:
      - checkout

      - run:
          command: npm install

      - run:
          command: node se.js

workflows:
   version: 2
   on_schedule:
    jobs:
      - build
    triggers:
      - schedule:
          # test on schedule using cron syntax
          cron: "55 13 * * *" # every hour
            filters:
              branches:
                only:
                  - master
